export type EnvSpecSection = {
  id: string;
  title: string;
  type: "intro" | "code" | "fields" | "table" | "list" | "sub-section";
  content?: string;
  code?: readonly string[];
  headers?: readonly string[];
  rows?: readonly (readonly string[])[];
  items?: readonly string[];
  subsections?: readonly EnvSpecSection[];
};

export const envSpecNav = [
  { href: "/docs/", label: "Documentation", icon: "book" },
  { id: "env-spec-overview", label: "Overview", icon: "terminal" },
  { id: "env-spec-commands", label: "Commands", icon: "terminal" },
  { id: "env-spec-structure", label: "Spec Structure", icon: "terminal" },
  { id: "env-spec-network", label: "Network", icon: "network" },
  { id: "env-spec-key", label: "Key", icon: "archive" },
  { id: "env-spec-image", label: "Image", icon: "archive" },
  { id: "env-spec-kernel", label: "Kernel", icon: "archive" },
  { id: "env-spec-binary", label: "Binary", icon: "archive" },
  { id: "env-spec-vm", label: "VM", icon: "terminal" },
  { id: "env-spec-exec", label: "Exec", icon: "terminal" },
  { id: "env-spec-ssh", label: "SSH", icon: "terminal" },
  { id: "env-spec-copy", label: "Copy", icon: "terminal" },
  { id: "env-spec-dependencies", label: "Dependencies", icon: "terminal" },
  { id: "env-spec-destroy", label: "Destroy Behavior", icon: "terminal" },
  { id: "env-spec-example", label: "Full Example", icon: "terminal" },
  { id: "env-spec-realworld", label: "Real-World Examples", icon: "terminal" },
  { id: "env-spec-state", label: "State File", icon: "terminal" },
] as const;

export const envSpecSections: readonly EnvSpecSection[] = [
  {
    id: "env-spec-overview",
    title: "Overview",
    type: "intro",
    content:
      "The environment workflow engine lets you define a complete VM environment — networks, keys, images, kernels, binaries, VMs, and provisioning steps — in a single YAML spec file. The engine provisions everything in dependency order, tracks what was created, and tears it all down on destroy.",
  },
  {
    id: "env-spec-commands",
    title: "Commands",
    type: "code",
    code: [
      "mvm env apply <spec-path>     # Provision everything in the spec",
      "mvm env ls                    # List applied environments",
      "mvm env diff <spec-path>      # Show what would change (spec vs state)",
      "mvm env destroy <wf-id|path>  # Tear down exactly what was provisioned",
    ],
  },
  {
    id: "env-spec-structure",
    title: "Spec Structure",
    type: "code",
    code: [
      "version: \"1\"",
      "",
      "network:",
      "  - name: <step-name>",
      "    # ... fields",
      "",
      "key:",
      "  - name: <step-name>",
      "    # ... fields",
      "",
      "image:",
      "  - name: <step-name>",
      "    # ... fields",
      "",
      "kernel:",
      "  - name: <step-name>",
      "    # ... fields",
      "",
      "binary:",
      "  - name: <step-name>",
      "    # ... fields",
      "",
      "vm:",
      "  - name: <step-name>",
      "    # ... fields",
      "",
      "ssh:",
      "  - name: <step-name>",
      "    # ... fields",
      "",
      "exec:",
      "  - name: <step-name>",
      "    # ... fields",
      "",
      "copy:",
      "  - name: <step-name>",
      "    # ... fields",
    ],
  },
  {
    id: "env-spec-network",
    title: "Network",
    type: "fields",
    content: "Create a network for VMs to connect to.",
    headers: ["Field", "Type", "Required", "Default", "Description"],
    rows: [
      ["name", "string", "Yes", "—", "Step name. Becomes <code>\"network:name\"</code>."],
      ["subnet", "string", "Yes", "—", "CIDR notation, e.g. <code>\"172.27.0.0/24\"</code>."],
      ["nat_enabled", "bool", "No", "true", "Enable NAT for internet access."],
      ["ipv4_gateway", "string", "No", "auto", "Gateway IP. Auto-computed from subnet if omitted."],
      ["nat_gateways", "[]string", "No", "auto", "Host interfaces for NAT. Auto-detected if empty."],
      ["default", "bool", "No", "false", "Set as default network for VM creation."],
    ],
    code: [
      "network:",
      "  - name: default",
      "    subnet: \"172.27.0.0/24\"",
      "    nat_enabled: true",
      "    default: true",
    ],
  },
  {
    id: "env-spec-key",
    title: "Key",
    type: "fields",
    content: "Generate or import an SSH key pair.",
    headers: ["Field", "Type", "Required", "Default", "Description"],
    rows: [
      ["name", "string", "Yes", "—", "Step name. Becomes <code>\"key:name\"</code>."],
      ["algorithm", "string", "No", "ed25519", "Key algorithm: <code>ed25519</code>, <code>rsa</code>, <code>ecdsa</code>."],
      ["bits", "int", "No", "0", "Key bits in RSA. 0 = algorithm default (4096 for RSA)."],
      ["comment", "string", "No", "auto", "Key comment."],
      ["force", "bool", "No", "false", "Overwrite existing key files."],
      ["default", "bool", "No", "false", "Set as default key for VM creation."],
    ],
    code: [
      "key:",
      "  - name: main-key",
      "    algorithm: ed25519",
      "    default: true",
    ],
  },
  {
    id: "env-spec-image",
    title: "Image",
    type: "fields",
    content: "Download an OS image.",
    headers: ["Field", "Type", "Required", "Default", "Description"],
    rows: [
      ["name", "string", "Yes", "—", "Step name. Becomes <code>\"image:name\"</code>."],
      ["type", "string", "Yes", "—", "Image type/slug, e.g. <code>ubuntu</code>, <code>alpine</code>."],
      ["version", "string", "No", "latest", "Version tag, e.g. <code>24.04</code>."],
      ["force", "bool", "No", "false", "Force re-pull even if exists."],
      ["default", "bool", "No", "false", "Set as default image."],
      ["partition", "int", "No", "0", "Partition index. 0 = auto-detect."],
      ["skip_optimization", "bool", "No", "false", "Skip image optimization."],
      ["disabled_detectors", "[]string", "No", "[]", "Disable detection methods: <code>type</code>, <code>label</code>, <code>size</code>, <code>filesystem</code>, <code>all</code>."],
    ],
    code: [
      "image:",
      "  - name: os-image",
      "    type: alpine",
      "    version: \"3.21\"",
    ],
  },
  {
    id: "env-spec-kernel",
    title: "Kernel",
    type: "fields",
    content: "Download or build a kernel.",
    headers: ["Field", "Type", "Required", "Default", "Description"],
    rows: [
      ["name", "string", "Yes", "—", "Step name. Becomes <code>\"kernel:name\"</code>."],
      ["type", "string", "Yes", "—", "Kernel type: <code>firecracker</code> or <code>official</code>."],
      ["version", "string", "No", "latest", "Version tag."],
      ["jobs", "int", "No", "CPU count", "Build parallelism (official kernel only)."],
      ["keep_build_dir", "bool", "No", "false", "Keep build directory after build."],
      ["clean_build", "bool", "No", "false", "Force clean build (skip cache)."],
      ["default", "bool", "No", "false", "Set as default kernel."],
      ["features", "string", "No", "", "Comma-separated features, e.g. <code>kvm,nftables</code>."],
    ],
    code: [
      "kernel:",
      "  - name: default-kernel",
      "    type: firecracker",
    ],
  },
  {
    id: "env-spec-binary",
    title: "Binary",
    type: "fields",
    content: "Download Firecracker binaries.",
    headers: ["Field", "Type", "Required", "Default", "Description"],
    rows: [
      ["name", "string", "Yes", "—", "Step name. Becomes <code>\"binary:name\"</code>."],
      ["type", "string", "No", "firecracker", "Binary type. Valid values: <code>firecracker</code>."],
      ["version", "string", "Yes", "—", "Version tag, e.g. <code>1.15.0</code>."],
      ["git_ref", "string", "No", "", "Build from git ref instead of downloading."],
      ["default", "bool", "No", "false", "Set as default binary."],
      ["force", "bool", "No", "false", "Force re-download."],
    ],
    code: [
      "binary:",
      "  - name: fc-binary",
      "    type: firecracker",
      "    version: \"1.15.0\"",
      "    default: true",
    ],
  },
  {
    id: "env-spec-vm",
    title: "VM",
    type: "fields",
    content: "Create a virtual machine.",
    headers: ["Field", "Type", "Required", "Default", "Description"],
    rows: [
      ["name", "string", "Yes", "—", "Step name. Becomes <code>\"vm:name\"</code>."],
      ["network", "string", "No", "default", "Network name/ID (step reference resolves to ID)."],
      ["key", "string", "No", "default", "Single SSH key name (shorthand for <code>ssh_keys</code>)."],
      ["ssh_keys", "[]string", "No", "[]", "List of SSH key names."],
      ["image", "string", "No", "default", "Image name/ID."],
      ["kernel", "string", "No", "default", "Kernel name/ID."],
      ["binary", "string", "No", "default", "Binary name/ID."],
      ["vcpu", "int", "No", "config", "vCPU count. Range: 1-32."],
      ["mem", "string", "No", "config", "Memory size (<code>512M</code>, <code>1G</code>, or bare MiB)."],
      ["disk_size", "string", "No", "config", "Disk size, e.g. <code>20G</code>."],
      ["user", "string", "No", "config", "SSH user for the VM."],
      ["pci_enabled", "bool", "No", "config", "Enable PCI support."],
      ["nested_virt", "bool", "No", "config", "Enable nested virtualization (requires PCI)."],
      ["console_enable", "bool", "No", "config", "Enable serial console."],
      ["guest_ip", "string", "No", "", "Request specific guest IP."],
      ["guest_mac", "string", "No", "", "Request specific MAC address."],
      ["volumes", "[]string", "No", "[]", "Volume names to attach."],
      ["count", "int", "No", "1", "Batch count for creating multiple VMs."],
      ["atomic", "bool", "No", "false", "Atomic batch creation (all or nothing)."],
      ["vsock_port", "int", "No", "1024", "Vsock port for guest agent."],
    ],
  },
  {
    id: "env-spec-exec",
    title: "Exec",
    type: "fields",
    content: "Run a command inside a VM via the vsock guest agent. Imperative — always re-runs on re-apply.",
    headers: ["Field", "Type", "Required", "Default", "Description"],
    rows: [
      ["name", "string", "Yes", "—", "Step name. Becomes <code>\"exec:name\"</code>."],
      ["target", "string", "Yes", "—", "VM name, ID prefix, IP, or MAC address."],
      ["cmd", "string", "Yes", "—", "Command to execute. Wrapped in <code>sh -c</code>."],
      ["user", "string", "No", "config", "User to run the command as."],
      ["timeout", "int", "No", "0", "Command timeout in seconds. 0 = no timeout."],
      ["port", "int", "No", "0", "Vsock agent port override. 0 = default."],
      ["env", "map", "No", "{}", "Environment variable overrides for the command."],
    ],
    code: [
      "exec:",
      "  - name: setup-app",
      "    target: dev-vm",
      "    cmd: \"./deploy.sh\"",
      "    user: root",
      "    timeout: 30",
      "    depends_on:",
      "      - vm:dev-vm",
    ],
  },
  {
    id: "env-spec-ssh",
    title: "SSH",
    type: "fields",
    content: "Run a command on a VM via SSH. Imperative — always re-runs on re-apply.",
    headers: ["Field", "Type", "Required", "Default", "Description"],
    rows: [
      ["name", "string", "Yes", "—", "Step name. Becomes <code>\"ssh:name\"</code>."],
      ["target", "string", "Yes", "—", "VM name, ID prefix, IP, or MAC address."],
      ["user", "string", "No", "config", "SSH user."],
      ["key", "string", "No", "config", "Key name or file path."],
      ["cmd", "string", "No", "", "Command to execute."],
      ["timeout", "int", "No", "0", "Connection timeout in seconds."],
      ["env", "map", "No", "{}", "Environment variable overrides."],
    ],
  },
  {
    id: "env-spec-copy",
    title: "Copy",
    type: "fields",
    content: "Copy files between host and VM via vsock binary frame protocol. Imperative — always re-runs on re-apply.",
    headers: ["Field", "Type", "Required", "Default", "Description"],
    rows: [
      ["name", "string", "Yes", "—", "Step name. Becomes <code>\"copy:name\"</code>."],
      ["src", "string", "Yes", "—", "Source path(s). Single string or array."],
      ["dest", "string", "Yes", "—", "Destination in <code>vm-name:/remote/path</code> format."],
      ["force", "bool", "No", "false", "Force overwrite existing files."],
    ],
  },
  {
    id: "env-spec-dependencies",
    title: "Dependencies",
    type: "intro",
    content:
      "Steps can declare dependencies on other steps using <code>depends_on</code>. The engine uses these to build a DAG and execute steps in dependency order. Format: <code>\"type:name\"</code> — singular type prefix + step name. The VM step also automatically infers dependencies from reference fields (<code>network</code>, <code>key</code>, <code>image</code>, <code>kernel</code>, <code>binary</code>). Apply runs levels 0→N; destroy runs N→0.",
    code: [
      "vm:",
      "  - name: dev-vm",
      "    depends_on:",
      "      - network:default",
      "      - key:main-key",
      "      - image:os-image",
    ],
  },
  {
    id: "env-spec-destroy",
    title: "Destroy Behavior",
    type: "table",
    headers: ["Step Type", "Behavior on Destroy"],
    rows: [
      ["network", "Deleted — NAT rules, bridge/tap, DB record removed"],
      ["key", "Deleted — key files removed, DB record removed"],
      ["vm", "Deleted — Firecracker killed, TAP removed, lease released, volumes detached, DB record deleted"],
      ["image", "Preserved — cached asset, shared across environments"],
      ["kernel", "Preserved — cached asset, shared across environments"],
      ["binary", "Preserved — cached asset, shared across environments"],
      ["ssh", "No-op — ephemeral side-effect"],
      ["exec", "No-op — ephemeral side-effect"],
      ["copy", "No-op — ephemeral side-effect"],
    ],
  },
  {
    id: "env-spec-example",
    title: "Full Example",
    type: "code",
    code: [
      "version: \"1\"",
      "",
      "network:",
      "  - name: default",
      "    subnet: \"172.27.0.0/24\"",
      "    nat_enabled: true",
      "    default: true",
      "",
      "key:",
      "  - name: main-key",
      "    algorithm: ed25519",
      "    default: true",
      "",
      "image:",
      "  - name: os-image",
      "    type: alpine",
      "    version: \"3.21\"",
      "",
      "kernel:",
      "  - name: default-kernel",
      "    type: firecracker",
      "",
      "binary:",
      "  - name: fc-binary",
      "    type: firecracker",
      "    version: \"1.15.0\"",
      "    default: true",
      "",
      "vm:",
      "  - name: dev-vm",
      "    network: default",
      "    key: main-key",
      "    image: os-image",
      "    kernel: default-kernel",
      "    binary: fc-binary",
      "    vcpu: 2",
      "    mem: 2048",
      "    disk_size: 10G",
      "    depends_on:",
      "      - network:default",
      "      - key:main-key",
      "      - image:os-image",
      "      - kernel:default-kernel",
      "      - binary:fc-binary",
      "",
      "ssh:",
      "  - name: setup-hostname",
      "    target: dev-vm",
      "    user: root",
      "    cmd: \"hostnamectl set-hostname my-dev-vm\"",
      "    depends_on:",
      "      - vm:dev-vm",
      "",
      "exec:",
      "  - name: bootstrap-app",
      "    target: dev-vm",
      "    cmd: \"curl -sS https://example.com/bootstrap.sh | sh\"",
      "    user: root",
      "    timeout: 60",
      "    depends_on:",
      "      - vm:dev-vm",
    ],
  },
  {
    id: "env-spec-realworld",
    title: "Real-World Examples",
    type: "intro",
    content:
      "Two production env specs from the mvmctl project itself. These demonstrate real usage patterns including multi-step copy pipelines, nested virtualization, and complex dependency ordering.",
    subsections: [
      {
        id: "env-spec-realworld-rc",
        title: "Release Candidate Test Environment (rc-env.yaml)",
        type: "code",
        code: [
          "version: \"1\"",
          "network:",
          "  - name: rc-net",
          "    subnet: 10.8.0.0/24",
          "    nat_enabled: true",
          "    default: true",
          "key:",
          "  - name: rc-key",
          "    algorithm: ed25519",
          "    default: true",
          "    force: true",
          "image:",
          "  - name: ubuntu-noble",
          "    type: ubuntu",
          "    version: noble",
          "    default: true",
          "binary:",
          "  - name: fc-16",
          "    type: firecracker",
          "    version: 1.16.0",
          "    default: true",
          "kernel:",
          "  - name: rc-vmlinux",
          "    type: official",
          "    version: 7.0.11",
          "    default: true",
          "    features: kvm,nftables,tuntap",
          "vm:",
          "  - name: rc-vm",
          "    depends_on:",
          "      - \"network:rc-net\"",
          "      - \"key:rc-key\"",
          "      - \"image:ubuntu-noble\"",
          "      - \"binary:fc-16\"",
          "      - \"kernel:rc-vmlinux\"",
          "    disk_size: 15G",
          "    vcpu: 6",
          "    mem: 4G",
          "    nested_virt: true",
          "    user: runner",
          "    network: rc-net",
          "    image: ubuntu-noble",
          "    kernel: rc-vmlinux",
          "    binary: fc-16",
          "copy:",
          "  - name: copy mvm",
          "    depends_on: [\"vm:rc-vm\"]",
          "    src: ./dist/mvm",
          "    dest: rc-vm:/root/",
          "  - name: copy firecracker tarball",
          "    depends_on: [\"vm:rc-vm\"]",
          "    src: ~/.cache/mvm-asset-mirror/firecracker-v1.16.0-x86_64.tgz",
          "    dest: rc-vm:/mnt/",
          "  - name: copy kernel",
          "    depends_on: [\"vm:rc-vm\"]",
          "    src: ~/.cache/mvm-asset-mirror/kernel-cache-7.0.11-eddb0bcef9946d7d.vmlinux",
          "    dest: rc-vm:/mnt/",
          "  - name: copy system tests",
          "    depends_on: [\"vm:rc-vm\"]",
          "    src: ./tests/",
          "    dest: rc-vm:/home/runner/tests/",
          "exec:",
          "  - name: install packages",
          "    depends_on: [\"vm:rc-vm\"]",
          "    target: rc-vm",
          "    user: root",
          "    timeout: 120",
          "    cmd: |",
          "      apt-get update && apt-get install -y qemu-utils python3-pip \\",
          "        docker.io cloud-image-utils build-essential &&",
          "      pip3 install pytest pytest-timeout &&",
          "      groupadd --force mvm && usermod -aG mvm runner",
          "  - name: install mvm",
          "    depends_on: [\"vm:rc-vm\", \"copy:copy mvm\"]",
          "    target: rc-vm",
          "    user: root",
          "    timeout: 60",
          "    cmd: |",
          "      cp /root/mvm /usr/bin/mvm",
          "  - name: import cached assets",
          "    depends_on: [\"vm:rc-vm\", \"exec:install mvm\"]",
          "    target: rc-vm",
          "    user: root",
          "    timeout: 300",
          "    env:",
          "      MVM_ASSET_MIRROR: /mnt",
          "    cmd: |",
          "      mvm init --non-interactive --skip-host",
          "      mvm kernel pull --type firecracker --default",
          "      mvm image pull ubuntu:noble",
          "      mvm bin pull firecracker --version 1.16.0 --default",
        ],
      },
      {
        id: "env-spec-realworld-builder",
        title: "Package Builder Environment (packaging/builder.yaml)",
        type: "code",
        code: [
          "version: \"1\"",
          "network:",
          "  - name: builder",
          "    subnet: \"172.30.0.0/24\"",
          "    nat: true",
          "key:",
          "  - name: builder",
          "    algorithm: ed25519",
          "    force: true",
          "image:",
          "  - name: ubuntu-builder",
          "    type: ubuntu",
          "    version: \"24.04\"",
          "kernel:",
          "  - name: krnl-builder",
          "    type: official",
          "    version: 7.0.11",
          "    features: nftables,tuntap,kvm,btrfs",
          "binary:",
          "  - name: fc-binary",
          "    type: firecracker",
          "    version: \"1.16.0\"",
          "vm:",
          "  - name: pkg-builder",
          "    network: builder",
          "    key: builder",
          "    image: ubuntu-builder",
          "    kernel: krnl-builder",
          "    binary: fc-binary",
          "    disk_size: 8G",
          "    vcpu: 4",
          "    mem: 3G",
          "    depends_on:",
          "      - network:builder",
          "      - key:builder",
          "      - image:ubuntu-builder",
          "      - kernel:krnl-builder",
          "      - binary:fc-binary",
          "copy:",
          "  - name: copy-scripts",
          "    src: ./scripts",
          "    dest: pkg-builder:/mnt/mvmctl/",
          "    force: true",
          "    depends_on:",
          "      - vm:pkg-builder",
          "  - name: copy-packaging",
          "    src: ./packaging",
          "    dest: pkg-builder:/mnt/mvmctl/",
          "    force: true",
          "    depends_on:",
          "      - vm:pkg-builder",
          "  - name: copy-source",
          "    src: ./internal",
          "    dest: pkg-builder:/mnt/mvmctl/",
          "    force: true",
          "    depends_on:",
          "      - vm:pkg-builder",
          "  - name: copy-pkg",
          "    src: ./pkg",
          "    dest: pkg-builder:/mnt/mvmctl/",
          "    force: true",
          "    depends_on:",
          "      - vm:pkg-builder",
          "  - name: copy-cmd",
          "    src: ./cmd",
          "    dest: pkg-builder:/mnt/mvmctl/",
          "    force: true",
          "    depends_on:",
          "      - vm:pkg-builder",
          "  - name: copy-gomod",
          "    src: ./go.mod",
          "    dest: pkg-builder:/mnt/mvmctl/go.mod",
          "    force: true",
          "    depends_on:",
          "      - vm:pkg-builder",
          "  - name: copy-gosum",
          "    src: ./go.sum",
          "    dest: pkg-builder:/mnt/mvmctl/go.sum",
          "    force: true",
          "    depends_on:",
          "      - vm:pkg-builder",
          "exec:",
          "  - name: build-all",
          "    target: pkg-builder",
          "    user: root",
          "    timeout: 30",
          "    cmd: |",
          "      export DEBIAN_FRONTEND=noninteractive &&",
          "      apt-get update -qq &&",
          "      apt-get install -y -qq debhelper build-essential rpm &&",
          "      cd /mnt/mvmctl &&",
          "      ./scripts/build-packages.sh --build-binaries --version ${VERSION}",
          "copy:",
          "  - name: retrieve-all",
          "    src: pkg-builder:/mnt/mvmctl/dist/packages/",
          "    dest: ./dist/packages",
          "    force: true",
          "    depends_on:",
          "      - exec:build-all",
        ],
      },
    ],
  },
  {
    id: "env-spec-state",
    title: "State File",
    type: "intro",
    content:
      "After running <code>mvm env apply</code>, the engine persists state to <code>~/.cache/mvmctl/workflows/&lt;workflow-id&gt;/state.yaml</code>. State is written after every successful step (crash-resilient). Re-running picks up where it left off.",
    code: [
      "workflow_id: \"ec729934a8fb9c67\"",
      "spec_path: \"./my-env.yaml\"",
      "schema_version: \"1.0\"",
      "resources:",
      "  - name: \"network:default\"",
      "    type: \"network\"",
      "    state:",
      "      spec:",
      "        network_id: \"net-abc123\"",
      "        subnet: \"172.27.0.0/24\"",
      "      meta:",
      "        was_created: true",
      "        spec_hash: \"a1b2c3...\"",
    ],
  },
];
